//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by BDC.rc
//
#define IDC_NAME                        1000
#define IDC_DAYSINADVANCE               1000
#define IDB_BALLOONS                    1001
#define IDC_WARNDAILY                   1001
#define IDC_BD_MONTH                    1002
#define IDD_SETBIRTHDAY                 1002
#define IDB_BALLOONS_KNOWN              1002
#define IDC_WARNANNOYINGLY              1002
#define IDC_BD_DAY                      1003
#define IDB_PREFSLOGO                   1003
#define IDD_PREFS_DIALOG                1004
#define IDC_VERSION                     1004
#define IDB_BALLOONS_CONFIRMED          1004
#define IDC_BD_YEAR                     1004
#define IDC_INFO                        1005
#define IDB_BALLOONS_TODAY              1005
#define IDD_IMPORT                      1005
#define IDC_KEEPUNTILCONFIRMED          1006
#define IDD_ANNOY_DIALOG                1006
#define IDC_IMPORTICQ                   1007
#define IDC_INSTRUCTIONS                1008
#define IDB_BALLOONS_DIALOG             1009
#define IDC_DISCLAIMER                  1009
#define IDC_RETRY                       1009
#define IDC_VERSIONHISTORY              1010
#define IDC_SKIP                        1010
#define IDB_VCF                         1010
#define IDR_INSTRUCTIONS                1011
#define IDC_IMPORTVCF                   1011
#define IDB_WAB                         1011
#define IDR_DISCLAIMER                  1012
#define IDC_REPORT                      1012
#define IDC_IMPORTWAB                   1012
#define IDR_VERSIONHISTORY              1013
#define IDC_DRAWRIGHTICONS              1013
#define IDR_BALLOONSAVI                 1014
#define IDC_ANIMATE                     1014
#define IDC_DRAWLEFTINFO                1014
#define IDB_TODAY                       1016
#define IDC_ALERTTEXT                   1017
#define IDC_SUFFIX_AGE                  1019
#define IDC_SUFFIX_YOB                  1020
#define IDC_SUFFIX_YOB_SHORT            1021
#define IDC_SUFFIX_NONE                 1022
#define IDC_SUFFIX_DATE                 1023

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1017
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1020
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
